import { EmbedBuilder } from "discord.js";

export async function sendHelp(message) {

  const embed = new EmbedBuilder()
    .setColor(0xffd700)
    .setTitle("🔎 Help")
    .addFields(
      { name: "Usage: ", value: "!roulette *optional <class>*", inline: true },
    )
    .setFooter({ text: "Generated by Finals Roulette Bot" });

  await message.reply({ embeds: [embed] });
}