import { generateRandomLoadout } from "../data/loadoutGenerator.js";
import { EmbedBuilder } from "discord.js";

export async function sendLoadout(message) {
  const loadout = generateRandomLoadout();

  const embed = new EmbedBuilder()
    .setColor(0xffd700)
    .setTitle("🎲 Random Loadout")
    .addFields(
      { name: "Class", value: loadout.className, inline: true },
      { name: "Weapon", value: loadout.weapon, inline: true },
      { name: "Ability", value: loadout.ability, inline: true },
      { name: "Equipment", value: loadout.equipment.join(", "), inline: false }
    )
    .setFooter({ text: "Generated by Finals Roulette Bot" });

  await message.reply({ embeds: [embed] });
}